return PlaceObj('ModDef', {
	'title', "Mass Production",
	'description', "Mostly late game QoL enhancement that enables more character autonomy through mass production and automated production.\nIntroduces multiple new buildings and devices, including granting access to fabricators outside of the military outpost scenario, albeit requiring a high level intellect and construction skills in your survivors (10 each) to research.",
	'image', "Mod/H5Xfcfc/Images/Screenshot 2024-01-20 101507 2.png",
	'last_changes', "Added GE Glitter Caps\nAdded GE Stone Leaf",
	'id', "H5Xfcfc",
	'author', "Godboss",
	'version_major', 2,
	'version_minor', 2,
	'version', 1216,
	'lua_revision', 233360,
	'saved_with_revision', 347716,
	'code', {
		"Building/MassPrint_Upgraded_Large_Drying_Rack.lua",
		"Building/MassPrint_Upgraded_Small_Drying_Rack.lua",
		"Building/FarmField_MassPrint_GE_Stoneleaf.lua",
		"Building/FarmField_MassPrint_GE_Oreleaf.lua",
		"Building/FarmField_MassPrint_GE_Siliconleaf.lua",
		"Building/FarmField_MassPrint_GE_EnergyCrystals.lua",
		"Building/FarmField_MassPrint_GE_GrainGrass.lua",
		"Building/FarmField_MassPrint_GE_Buttermelon.lua",
		"Building/FarmField_MassPrint_GE_ChewRoots.lua",
		"Building/FarmField_MassPrint_GE_RedMeat.lua",
		"Building/FarmField_MassPrint_GE_ChitinMeat.lua",
		"Building/FarmField_MassPrint_GE_GlitterCap.lua",
		"Building/MassClothingPrinter3D.lua",
		"Building/MassEquipmentPrinter3D.lua",
		"Building/MassPrint_Improved_CarbonBed_Cloth.lua",
		"Building/MassPrint_Improved_CarbonBed_Synthetics.lua",
		"Building/MassPrint_Lightning_rod.lua",
		"Building/MassPrint_StoragePit_1.lua",
		"Building/MassPrint_StoragePit_2.lua",
		"Building/MassPrint_StoragePit_3.lua",
		"Building/MassPrint_Solar_Panel_Smart.lua",
		"Building/MassPrint_Improved_Solar_Panel_Smart.lua",
		"Building/MassPrint_Graphene_Solar_Panel_Smart.lua",
		"Building/MassPrint_Wind_Smart.lua",
		"Building/MassPrint_Carbon_Wind_Smart.lua",
		"Building/MassPrint_DieselGenerator_Smart.lua",
		"Building/MassPrint_PowerCellGenerator_Smart.lua",
		"Building/MassPrint_Composter_Metal.lua",
		"Building/MassPrint_Composter_Wood.lua",
		"Building/MassPrint_MotionSensor_Smart.lua",
	},
	'has_data', true,
	'saved', 1706179280,
	'code_hash', -2765265260827150694,
	'steam_id', "2958775360",
	'TagBuildings', true,
	'TagGameplay', true,
	'TagPlants', true,
	'TagResearch', true,
})