return PlaceObj('ModDef', {
	'title', "Mass Production",
	'description', "Mostly late game QoL enhancement that enables more character autonomy through mass production and automated production.\nIntroduces multiple new buildings and devices, including granting access to fabricators outside of the military outpost scenario, albeit requiring a high level intellect and construction skills in your survivors (10 each) to research.",
	'last_changes', "- Made small veggie drying rack also consume electricity\n- Enabled the turn off option for both drying racks",
	'id', "H5Xfcfc",
	'author', "Godboss",
	'version_major', 1,
	'version_minor', 1,
	'version', 685,
	'lua_revision', 233360,
	'saved_with_revision', 347716,
	'code', {
		"Building/MassPrint_Upgraded_Large_Drying_Rack.lua",
		"Building/MassPrint_Upgraded_Small_Drying_Rack.lua",
		"Building/FarmField_MassPrint_Oreleaf.lua",
		"Building/MassClothingPrinter3D.lua",
		"Building/MassEquipmentPrinter3D.lua",
		"Building/MassPrint_Improved_CarbonBed_Cloth.lua",
		"Building/MassPrint_Improved_CarbonBed_Synthetics.lua",
	},
	'has_data', true,
	'saved', 1703609448,
	'code_hash', -8500236222139341755,
	'steam_id', "2958775360",
	'TagBuildings', true,
	'TagGameplay', true,
	'TagPlants', true,
	'TagResearch', true,
})