UndefineClass('MassPrint_DieselGenerator_Smart')
DefineClass.MassPrint_DieselGenerator_Smart = {
	__parents = { "Building", "MalfunctionOverTimeComponent", "PowerComponent", "ResConsumerDeviceComponent" },
	__generated_by_class = "ModItemBuildingCompositeDef",


	object_class = "Building",
	LockState = "hidden",
	unload_anim_hands = "standing_DropDown_Hands",
	load_anim_hands = "standing_PickUp_Hands",
	BuildMenuCategory = "MassPrint_ImprovedPowerMenu",
	display_name = T(793175477654, --[[ModItemBuildingCompositeDef MassPrint_DieselGenerator_Smart display_name]] "Smart Diesel generator"),
	description = T(770478317642, --[[ModItemBuildingCompositeDef MassPrint_DieselGenerator_Smart description]] "Adding a built-in CPU and basic AI algorithms to optimize the diesel generator operations you will be able to increase Power Production & Durability & Resource Consumption.\n\nGenerates <color TextEmphasis>250</color> <image 'UI/Icons/Resources/res_electricity' 1100> while burning fuel."),
	menu_display_name = T(325572918079, --[[ModItemBuildingCompositeDef MassPrint_DieselGenerator_Smart menu_display_name]] "Smart Diesel Generator"),
	BuildMenuIcon = "UI/Icons/Build Menu/diesel_generator",
	BuildMenuPos = 8,
	display_name_pl = T(886413970437, --[[ModItemBuildingCompositeDef MassPrint_DieselGenerator_Smart display_name_pl]] "Smart Diesel generators"),
	entity = "DieselGenerator",
	labels = {
		"PowerSources",
		"BerserkTargets",
	},
	update_interval = 10000,
	FinalColor = 4294445321,
	can_turn_off = true,
	construction_cost = PlaceObj('ConstructionCost', {
		CPUCore = 1000,
		LiquidFuel = 20000,
		Metal = 50000,
		ScrapElectronics = 10000,
	}),
	construction_points = 80000,
	repair_cost = PlaceObj('ConstructionCost', {
		Metal = 5000,
		ScrapElectronics = 2000,
	}),
	deconstruction_output = PlaceObj('ConstructionCost', {
		CPUCore = 1000,
		ScrapElectronics = 2000,
		ScrapMetal = 25000,
	}),
	Health = 250000,
	MaxHealth = 250000,
	lock_block_box = box(-300, -300, 0, 1800, 300, 1050),
	SkirtSize = 57,
	EntityHeight = 1136,
	BuildStartAnimation = "standing_Repair_Weld_Start",
	BuildIdleAnimations = {
		"standing_Repair_Weld_Idle",
	},
	BuildEndAnimation = "standing_Repair_Weld_End",
	BuildActivityTool = "WeldingTool",
	realtime_working_anim = true,
	attack_attraction = 20,
	enable_overlay_on_placement = {
		RoomsOverlay = true,
	},
	MalfunctionOverTimeComponent = true,
	PowerComponent = true,
	ResConsumerDeviceComponent = true,
	MinTimeToMalfunction = 57600000,
	MaxTimeToMalfunction = 86400000,
	IsPowerGenerator = true,
	Production = 250000,
	HasSmartConnection = true,
	res_consumed = "LiquidFuel",
	res_stored = 20000,
	res_operate_time = 3840000,
	res_start_fueled = true,
}

