UndefineClass('MassPrint_PowerCellGenerator_Smart')
DefineClass.MassPrint_PowerCellGenerator_Smart = {
	__parents = { "Building", "MalfunctionOverTimeComponent", "PowerComponent", "ResConsumerDeviceComponent" },
	__generated_by_class = "ModItemBuildingCompositeDef",


	object_class = "Building",
	unload_anim_hands = "standing_DropDown_Hands",
	load_anim_hands = "standing_PickUp_Hands",
	BuildMenuCategory = "MassPrint_ImprovedPowerMenu",
	display_name = T(566803911514, --[[ModItemBuildingCompositeDef MassPrint_PowerCellGenerator_Smart display_name]] "Smart Power cell generator"),
	description = T(931433170918, --[[ModItemBuildingCompositeDef MassPrint_PowerCellGenerator_Smart description]] "Adding a built-in CPU and basic AI algorithms to optimize the diesel generator operations you will be able to increase Power Production & Durability & Resource Consumption.\n\nGenerates <color TextEmphasis>Electricity</color> <image 'UI/Icons/Resources/res_electricity' 1100> while depleting a power cell."),
	BuildMenuIcon = "UI/Icons/Build Menu/power_cell_generator",
	BuildMenuPos = 9,
	display_name_pl = T(381670849476, --[[ModItemBuildingCompositeDef MassPrint_PowerCellGenerator_Smart display_name_pl]] "Smart Power cell generators"),
	entity = "PowerCellGenerator",
	labels = {
		"PowerSources",
		"BerserkTargets",
	},
	update_interval = 10000,
	FinalColor = 4294575879,
	can_turn_off = true,
	construction_cost = PlaceObj('ConstructionCost', {
		CPUCore = 1000,
		Metal = 20000,
		PowerCell = 1000,
		ScrapElectronics = 10000,
	}),
	construction_points = 40000,
	repair_cost = PlaceObj('ConstructionCost', {
		Metal = 10000,
	}),
	deconstruction_output = PlaceObj('ConstructionCost', {
		CPUCore = 1000,
		ScrapElectronics = 5000,
		ScrapMetal = 25000,
	}),
	Health = 500000,
	MaxHealth = 500000,
	lock_block_box = box(-300, -300, 0, 300, 300, 700),
	SkirtSize = 181,
	EntityHeight = 764,
	BuildStartAnimation = "kneel_Repair_Weld_Start",
	BuildIdleAnimations = {
		"kneel_Repair_Weld_Idle",
	},
	BuildEndAnimation = "kneel_Repair_Weld_End",
	BuildActivityTool = "WeldingTool",
	realtime_working_anim = true,
	attack_attraction = 20,
	enable_overlay_on_placement = {
		RoomsOverlay = true,
	},
	MalfunctionOverTimeComponent = true,
	PowerComponent = true,
	ResConsumerDeviceComponent = true,
	MinTimeToMalfunction = 57600000,
	MaxTimeToMalfunction = 86400000,
	IsPowerGenerator = true,
	Production = 500000,
	HasSmartConnection = true,
	res_consumed = "PowerCell",
	res_stored = 1000,
	res_operate_time = 38400000,
	res_request_threshold = 1,
	res_start_fueled = true,
}

